const producs=[
    {
        id:0,
        name:"کاپوچینو",
        price:18.500,
        instock:28,
        imgsrc:"./images/menu-1.png",
    },
    {
        id:1,
        name:"قهوه فرانسه",
        price:19,
        instock:30,
        imgsrc:"./images/menu-2.png",
    },
    {
        id:2,
        name:"لته",
        price:18.500,
        instock:28,
        imgsrc:"./images/menu-3.png",
    },
    {
        id:3,
        name:"موکاپوچینو",
        price:20,
        instock:28,
        imgsrc:"./images/menu-4.png",
    },
    {
        id:4,
        name:"موکا",
        price:25,
        instock:28,
        imgsrc:"./images/menu-5.png",
    },{
        id:5,
        name:"اسپرسو",
        price:17,
        instock:100,
        imgsrc:"./images/menu-6.png",
    },
]